-- MySQL Script generated by MySQL Workbench
-- Mon Sep 26 21:05:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TBLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TBLogin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TBLogin` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `id_Longin` (`idLogin` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `idEnderecoPrincipal` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT(5) NULL DEFAULT 0,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,address
  `CEP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEnderecoPrincipal`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEnderecoPrincipal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contacts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contacts` (
  `idContact` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `celular` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBClientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TBClientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TBClientes` (
  `idClient` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `CPF` INT(11) UNSIGNED NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `Login_id` INT NOT NULL,
  `endereço_idEnderecoPrincipal` INT NOT NULL,
  `contatos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_TBClientes_TBLogin_idx` (`Login_id` ASC) VISIBLE,
  INDEX `fk_TBClientes_endereço1_idx` (`endereço_idEnderecoPrincipal` ASC) VISIBLE,
  INDEX `fk_TBClientes_contatos1_idx` (`contatos_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `eventoo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEvento`),
  UNIQUE INDEX `idEvento_UNIQUE` (`idEvento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventAddress` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventAddress` (
  `idEndEvento` INT NOT NULL AUTO_INCREMENT,
  `cidadeEvento` VARCHAR(45) NOT NULL,
  `localEvento` VARCHAR(45) NOT NULL,
  `horaEvento` TIME NOT NULL,
  `dataEvento` DATE NOT NULL,
  PRIMARY KEY (`idEndEvento`),
  UNIQUE INDEX `cidade_UNIQUE` (`idEndEvento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_has_eventAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event_has_eventAddress` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event_has_eventAddress` (
  `eventos_idEvento` INT NOT NULL,
  `enderecoEvento_idEvento` INT NOT NULL,
  PRIMARY KEY (`eventos_idEvento`, `enderecoEvento_idEvento`),
  INDEX `fk_eventos_has_enderecoEvento_enderecoEvento1_idx` (`enderecoEvento_idEvento` ASC) VISIBLE,
  INDEX `fk_eventos_has_enderecoEvento_eventos1_idx` (`eventos_idEvento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  `eventos_idEvento` INT NOT NULL,
  PRIMARY KEY (`idGenero`, `genero`),
  UNIQUE INDEX `idGenero_UNIQUE` (`idGenero` ASC) VISIBLE,
  INDEX `fk_genero_eventos1_idx` (`eventos_idEvento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBClientes_has_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TBClientes_has_events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TBClientes_has_events` (
  `TBClientes_idClient` INT UNSIGNED NOT NULL,
  `events_idEvento` INT NOT NULL,
  PRIMARY KEY (`TBClientes_idClient`, `events_idEvento`),
  INDEX `fk_TBClientes_has_events_events1_idx` (`events_idEvento` ASC) VISIBLE,
  INDEX `fk_TBClientes_has_events_TBClientes1_idx` (`TBClientes_idClient` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
